### ISSUE TITLE
Getuserdata return null

### ISSUE THREAD

**Issue by HieuDuong7104** [amzker/chatapp-godot-firebase#1]
i don't know where the problem lies, because i logged in successfully but when getuserdata it returns null

![05-02-2024screenshot-00-14-53-375](https://github.com/amzker/chatapp-godot-firebase/assets/153789669/b0967e75-1add-49ed-8156-37da763903dd)
![05-02-2024screenshot-00-15-12-537](https://github.com/amzker/chatapp-godot-firebase/assets/153789669/f2c074c9-4226-4157-9c0e-924796a14175)

**Comment by amzker** [comment]
print req and chats 

i think because there is no data in your firebase database.


it's mistake in my code , as i made this code after there was data in realtime database, i overlooked it. just add this 
if retrned data is null then pass. 

now send messege , this way everything will be solved

**Comment by HieuDuong7104** [comment]
> In Hỏi Đáp và Trò chuyện
> 
> Tôi nghĩ vì không có dữ liệu trong cơ sở dữ liệu Firebase của bạn.
> 
> Đó là sai lầm trong mã của tôi, vì tôi đã tạo mã này sau khi có dữ liệu trong cơ sở dữ liệu thời gian thực, tôi đã bỏ qua nó. Chỉ cần thêm điều này nếu dữ liệu rút lại là null sau đó vượt qua.
> 
> Bây giờ gửi messege, theo cách này mọi thứ sẽ được giải quyết

I have corrected that error, thank you very much

**Comment by duonghieu7104** [comment]
> print req and chats
> 
> i think because there is no data in your firebase database.
> 
> it's mistake in my code , as i made this code after there was data in realtime database, i overlooked it. just add this if retrned data is null then pass.
> 
> now send messege , this way everything will be solved

I have corrected that error, thank you very much
